-- =============================================================================
-- Liga-Website – Grundschema (Plan §6)
--
-- Grundsätze:
--   * jede Tabelle hat id, created_at, updated_at
--   * Aufzählungen als text + CHECK (leichter erweiterbar als Postgres-Enums)
--   * geschrieben wird nur über den Server (Service-Key nach Rollenprüfung),
--     gelesen wird öffentlich nur über RLS-Policies (siehe *_rls.sql)
-- =============================================================================

create extension if not exists pgcrypto;

-- -----------------------------------------------------------------------------
-- Hilfsfunktionen
-- -----------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- -----------------------------------------------------------------------------
-- §6.5 Regelwerk (vor seasons, weil seasons darauf verweist)
-- -----------------------------------------------------------------------------

create table public.rules_versions (
  id              bigint generated by default as identity primary key,
  version         text not null unique,                 -- "1.0"
  effective_from  date,
  changelog_de    text not null default '',
  changelog_en    text,
  status          text not null default 'draft'
                  check (status in ('draft', 'published', 'archived')),
  published_at    timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table public.rules_sections (
  id          bigint generated by default as identity primary key,
  version_id  bigint not null references public.rules_versions (id) on delete cascade,
  parent_id   bigint references public.rules_sections (id) on delete cascade,
  number      text not null,                            -- "§3.2"
  anchor      text not null,                            -- "p3-2" (stabiler Anker)
  title_de    text not null,
  title_en    text,
  body_de     text not null default '',                 -- Markdown
  body_en     text,
  sort        integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (version_id, number),
  unique (version_id, anchor)
);
create index rules_sections_version_idx on public.rules_sections (version_id, sort);

-- -----------------------------------------------------------------------------
-- §6.1 Liga-Struktur
-- -----------------------------------------------------------------------------

create table public.points_schemes (
  id                   bigint generated by default as identity primary key,
  name                 text not null unique,
  race_points          integer[] not null,               -- Index 0 = P1
  sprint_points        integer[] not null default '{}',
  fastest_lap_bonus    integer not null default 0 check (fastest_lap_bonus >= 0),
  fastest_lap_max_pos  integer check (fastest_lap_max_pos is null or fastest_lap_max_pos > 0),
  pole_bonus           integer not null default 0 check (pole_bonus >= 0),
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

create table public.seasons (
  id                               bigint generated by default as identity primary key,
  number                           integer not null unique check (number > 0),
  slug                             text not null unique,
  name                             text not null,
  game_version                     text not null,        -- "F1 25 · 2026 Season Pack"
  status                           text not null default 'planned'
                                   check (status in ('planned', 'active', 'finished')),
  points_scheme_id                 bigint not null references public.points_schemes (id),
  reserve_points_for_constructors  boolean not null default true,
  protest_window_hours             integer not null default 48 check (protest_window_hours > 0),
  two_steward_rule                 boolean not null default false,
  penalty_points_enabled           boolean not null default false,
  lobby_settings                   jsonb not null default '{}'::jsonb,
  rules_version_id                 bigint references public.rules_versions (id),
  starts_on                        date,
  ends_on                          date,
  created_at                       timestamptz not null default now(),
  updated_at                       timestamptz not null default now()
);
-- höchstens eine aktive Saison
create unique index seasons_single_active_idx on public.seasons (status) where status = 'active';

create table public.tracks (
  id             bigint generated by default as identity primary key,
  slug           text not null unique,
  name_de        text not null,
  name_en        text not null,
  country_code   char(2) not null,                       -- ISO 3166-1 alpha-2
  game_track_id  integer,                                -- ID aus der UDP-Spezifikation
  length_km      numeric(5, 3),
  laps_default   integer,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table public.rounds (
  id                bigint generated by default as identity primary key,
  season_id         bigint not null references public.seasons (id) on delete cascade,
  number            integer not null check (number > 0),
  track_id          bigint not null references public.tracks (id),
  local_start       timestamp not null,                  -- Ortszeit (ohne TZ), gepflegt in `timezone`
  timezone          text not null default 'Europe/Berlin',
  start_utc         timestamptz not null,                -- per Trigger berechnet
  format            text not null default 'standard' check (format in ('standard', 'sprint')),
  status            text not null default 'scheduled'
                    check (status in ('scheduled', 'lineup_published', 'provisional', 'final', 'corrected', 'cancelled')),
  provisional_at    timestamptz,
  protest_deadline  timestamptz,                         -- per Trigger berechnet
  final_at          timestamptz,
  vod_url           text,
  highlights_url    text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (season_id, number)
);
create index rounds_start_idx on public.rounds (start_utc);

create or replace function public.rounds_compute_times()
returns trigger
language plpgsql
as $$
declare
  window_hours integer;
begin
  new.start_utc := new.local_start at time zone new.timezone;
  if new.provisional_at is not null then
    select s.protest_window_hours into window_hours from public.seasons s where s.id = new.season_id;
    new.protest_deadline := new.provisional_at + make_interval(hours => coalesce(window_hours, 48));
  else
    new.protest_deadline := null;
  end if;
  return new;
end;
$$;

create trigger rounds_compute_times
  before insert or update of local_start, timezone, provisional_at, season_id
  on public.rounds
  for each row execute function public.rounds_compute_times();

-- Korrekturen nach „final“ – öffentlich sichtbar mit Pflicht-Grund (Plan §5.2)
create table public.round_corrections (
  id          bigint generated by default as identity primary key,
  round_id    bigint not null references public.rounds (id) on delete cascade,
  reason_de   text not null check (length(trim(reason_de)) > 0),
  reason_en   text,
  created_by  uuid,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table public.sessions (
  id          bigint generated by default as identity primary key,
  round_id    bigint not null references public.rounds (id) on delete cascade,
  type        text not null check (type in ('qualifying', 'sprint', 'race')),
  weather     text,
  status      text not null default 'pending' check (status in ('pending', 'entered')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (round_id, type)
);

create table public.teams (
  id              bigint generated by default as identity primary key,
  slug            text not null unique,
  name            text not null,
  short_name      text not null,
  color_hex       text not null check (color_hex ~ '^#[0-9A-Fa-f]{6}$'),
  text_color_hex  text not null default '#000000' check (text_color_hex ~ '^#[0-9A-Fa-f]{6}$'),
  game_team_id    integer,
  active          boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table public.season_teams (
  season_id   bigint not null references public.seasons (id) on delete cascade,
  team_id     bigint not null references public.teams (id),
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  primary key (season_id, team_id)
);

-- -----------------------------------------------------------------------------
-- §6.2 Fahrer, Nummern, Cockpits
-- -----------------------------------------------------------------------------

create table public.drivers (
  id                bigint generated by default as identity primary key,
  slug              text not null unique,
  gamertag          text not null,
  nationality_code  char(2),
  platform          text not null check (platform in ('pc_steam', 'pc_ea', 'playstation', 'xbox')),
  input_device      text not null default 'controller' check (input_device in ('wheel', 'controller')),
  status            text not null default 'reserve' check (status in ('active', 'reserve', 'inactive', 'banned')),
  reserve_order     integer,                             -- Reihenfolge im Reservepool (Warteliste)
  joined_season_id  bigint references public.seasons (id),
  twitch_url        text,
  youtube_url       text,
  show_links        boolean not null default false,
  anonymized        boolean not null default false,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
-- Duplikat-Erkennung: Gamertag (normalisiert, case-insensitive) nur einmal
create unique index drivers_gamertag_unique_idx on public.drivers (lower(gamertag)) where not anonymized;

-- nur Admin: private Kontaktdaten
create table public.driver_private (
  driver_id         bigint primary key references public.drivers (id) on delete cascade,
  discord_user_id   text,
  discord_username  text,
  ea_id             text,
  notes             text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create table public.driver_numbers (
  id          bigint generated by default as identity primary key,
  driver_id   bigint not null references public.drivers (id) on delete cascade,
  number      integer not null check (number between 1 and 99),
  valid_from  timestamptz not null default now(),
  valid_to    timestamptz,
  note        text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  check (valid_to is null or valid_to > valid_from)
);
-- eine Nummer ist immer nur einmal aktiv vergeben, die Historie bleibt
create unique index driver_numbers_active_number_idx on public.driver_numbers (number) where valid_to is null;
-- ein Fahrer hat höchstens eine offene Nummer
create unique index driver_numbers_active_driver_idx on public.driver_numbers (driver_id) where valid_to is null;

create table public.seats (
  id          bigint generated by default as identity primary key,
  season_id   bigint not null references public.seasons (id) on delete cascade,
  team_id     bigint not null references public.teams (id),
  seat_no     smallint not null check (seat_no in (1, 2)),
  driver_id   bigint not null references public.drivers (id),
  from_round  integer not null default 1 check (from_round > 0),
  to_round    integer check (to_round is null or to_round >= from_round),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index seats_season_idx on public.seats (season_id);

create table public.round_entries (
  id                  bigint generated by default as identity primary key,
  round_id            bigint not null references public.rounds (id) on delete cascade,
  team_id             bigint not null references public.teams (id),
  seat_no             smallint not null check (seat_no in (1, 2)),
  driver_id           bigint not null references public.drivers (id),
  role                text not null default 'regular' check (role in ('regular', 'reserve')),
  replaces_driver_id  bigint references public.drivers (id),
  race_number         integer check (race_number between 1 and 99),   -- Snapshot zur Runde
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (round_id, driver_id),
  unique (round_id, team_id, seat_no)
);

create table public.round_absences (
  round_id          bigint not null references public.rounds (id) on delete cascade,
  driver_id         bigint not null references public.drivers (id) on delete cascade,
  reported_in_time  boolean not null default true,
  note              text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  primary key (round_id, driver_id)
);

-- -----------------------------------------------------------------------------
-- §6.3 Ergebnisse und Wertung
-- -----------------------------------------------------------------------------

create table public.results (
  id                       bigint generated by default as identity primary key,
  session_id               bigint not null references public.sessions (id) on delete cascade,
  round_entry_id           bigint references public.round_entries (id) on delete set null,
  driver_id                bigint not null references public.drivers (id),
  team_id                  bigint not null references public.teams (id),
  race_number              integer,
  role                     text not null default 'regular' check (role in ('regular', 'reserve')),
  entered_position         integer not null check (entered_position > 0),  -- Reihenfolge laut Eingabe
  position                 integer check (position is null or position > 0), -- nach Strafen, null = nicht gewertet
  status                   text not null default 'classified'
                           check (status in ('classified', 'dnf', 'dns', 'dsq', 'dnc')),
  grid_position            integer check (grid_position is null or grid_position > 0),
  laps                     integer check (laps is null or laps >= 0),
  total_time_ms            bigint check (total_time_ms is null or total_time_ms > 0),
  gap_ms                   bigint check (gap_ms is null or gap_ms >= 0),
  gap_laps                 integer check (gap_laps is null or gap_laps >= 0),
  best_lap_ms              integer check (best_lap_ms is null or best_lap_ms > 0),
  pit_stops                integer check (pit_stops is null or pit_stops >= 0),
  ingame_penalty_s         integer not null default 0 check (ingame_penalty_s >= 0),
  steward_penalty_s        integer not null default 0 check (steward_penalty_s >= 0),
  is_fastest_lap           boolean not null default false,
  is_pole                  boolean not null default false,
  points                   integer not null default 0,
  counts_for_constructors  boolean not null default true,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  unique (session_id, driver_id)
);
create index results_session_idx on public.results (session_id);
create index results_driver_idx on public.results (driver_id);

create table public.standings_snapshots (
  id              bigint generated by default as identity primary key,
  season_id       bigint not null references public.seasons (id) on delete cascade,
  after_round_id  bigint not null references public.rounds (id) on delete cascade,
  kind            text not null check (kind in ('driver', 'team')),
  entity_id       bigint not null,
  position        integer not null,
  points          integer not null,
  wins            integer not null default 0,
  podiums         integer not null default 0,
  poles           integer not null default 0,
  fastest_laps    integer not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (after_round_id, kind, entity_id)
);

create table public.awards (
  id          bigint generated by default as identity primary key,
  season_id   bigint not null references public.seasons (id) on delete cascade,
  round_id    bigint references public.rounds (id) on delete cascade,
  type        text not null check (type in ('champion', 'constructors', 'driver_of_the_day', 'rookie_of_the_year')),
  driver_id   bigint references public.drivers (id),
  team_id     bigint references public.teams (id),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- §6.4 Stewards
-- -----------------------------------------------------------------------------

create table public.incidents (
  id                   bigint generated by default as identity primary key,
  round_id             bigint not null references public.rounds (id) on delete cascade,
  session_id           bigint references public.sessions (id) on delete set null,
  reporter_driver_id   bigint references public.drivers (id),
  reporter_contact     text,                             -- Discord-Name für Rückfragen (bis Saisonende)
  involved_driver_ids  bigint[] not null default '{}',
  lap                  integer,
  corner               text,
  description          text not null,
  clip_url             text,                             -- Pflicht bei Meldungen, optional bei eigenen Untersuchungen
  clip_timestamp       text,
  submitted_at         timestamptz not null default now(),
  ip_hash              text,
  source               text not null default 'report' check (source in ('report', 'steward')),
  status               text not null default 'new'
                       check (status in ('new', 'in_review', 'decided', 'rejected', 'late')),
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create index incidents_round_idx on public.incidents (round_id);

create table public.decisions (
  id              bigint generated by default as identity primary key,
  public_ref      text not null unique,                  -- "S1-R03-02"
  incident_id     bigint references public.incidents (id) on delete set null,
  round_id        bigint not null references public.rounds (id) on delete cascade,
  session_id      bigint references public.sessions (id) on delete set null,
  driver_id       bigint not null references public.drivers (id),
  verdict         text not null check (verdict in (
                    'no_action', 'warning', 'time_penalty', 'position_penalty',
                    'grid_penalty_next', 'dsq', 'race_ban')),
  time_seconds    integer check (time_seconds is null or time_seconds > 0),
  positions       integer check (positions is null or positions > 0),
  penalty_points  integer check (penalty_points is null or penalty_points >= 0),   -- vorbereitet
  reasoning_de    text not null,
  reasoning_en    text,
  rule_ref        text,                                  -- z. B. "§5.3"
  clip_url        text,
  decided_by      uuid[] not null default '{}',
  status          text not null default 'draft' check (status in ('draft', 'published', 'revoked')),
  published_at    timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  check (verdict <> 'time_penalty' or time_seconds is not null),
  check (verdict not in ('position_penalty', 'grid_penalty_next') or positions is not null)
);
create index decisions_round_idx on public.decisions (round_id);

-- -----------------------------------------------------------------------------
-- §6.5 Inhalte (zweisprachig)
-- -----------------------------------------------------------------------------

create table public.news (
  id           bigint generated by default as identity primary key,
  slug_de      text not null unique,
  slug_en      text not null unique,
  title_de     text not null,
  title_en     text,
  excerpt_de   text not null default '',
  excerpt_en   text,
  body_de      text not null default '',                 -- Markdown
  body_en      text,
  cover_image  text,
  cover_alt_de text,
  cover_alt_en text,
  category     text not null default 'announcement'
               check (category in ('race_report', 'announcement', 'rule_change', 'new_drivers', 'community')),
  round_id     bigint references public.rounds (id) on delete set null,
  author_id    uuid,
  author_name  text,                                     -- Gamertag für die Anzeige
  status       text not null default 'draft' check (status in ('draft', 'scheduled', 'published')),
  publish_at   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index news_publish_idx on public.news (status, publish_at desc);

create table public.faq_items (
  id           bigint generated by default as identity primary key,
  category     text not null default 'general'
               check (category in ('general', 'requirements', 'raceday', 'technical', 'stewards')),
  question_de  text not null,
  question_en  text,
  answer_de    text not null,                            -- Markdown
  answer_en    text,
  sort         integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table public.staff_members (
  id            bigint generated by default as identity primary key,
  gamertag      text not null,
  role_de       text not null,
  role_en       text,
  avatar        text,
  since_season  integer,
  sort          integer not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table public.open_positions (
  id              bigint generated by default as identity primary key,
  title_de        text not null,
  title_en        text,
  description_de  text not null,
  description_en  text,
  effort          text,                                  -- "ca. 2 h pro Renntag"
  active          boolean not null default true,
  sort            integer not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table public.partners (
  id          bigint generated by default as identity primary key,
  name        text not null,
  logo        text,
  url         text not null,
  text_de     text not null default '',
  text_en     text,
  label_ad    boolean not null default true,             -- Kennzeichnung „Anzeige“
  active      boolean not null default true,
  sort        integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table public.settings (
  key         text primary key,
  value       jsonb not null,
  is_public   boolean not null default false,            -- nur öffentliche Schlüssel sind per RLS lesbar
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- §6.6 Anmeldung, Admin, Protokoll
-- -----------------------------------------------------------------------------

create table public.registrations (
  id                bigint generated by default as identity primary key,
  gamertag          text not null,
  discord_username  text not null,
  ea_id             text,
  platform          text not null check (platform in ('pc_steam', 'pc_ea', 'playstation', 'xbox')),
  input_device      text not null check (input_device in ('wheel', 'controller')),
  nationality       char(2),
  desired_number    integer not null check (desired_number between 1 and 99),
  wanted_role       text not null check (wanted_role in ('regular', 'reserve', 'any')),
  availability      text not null check (availability in ('regular', 'mostly', 'irregular')),
  experience        text,
  reference_time    text,
  consents          jsonb not null,                      -- {age16: true, rules: true, at: ..., rules_version: ...}
  status            text not null default 'new'
                    check (status in ('new', 'contacted', 'accepted', 'waitlist', 'rejected')),
  admin_notes       text,
  ip_hash           text,
  driver_id         bigint references public.drivers (id) on delete set null,
  processed_by      uuid,
  processed_at      timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index registrations_status_idx on public.registrations (status, created_at desc);

create table public.contact_messages (
  id          bigint generated by default as identity primary key,
  name        text not null,
  email       text not null,
  subject     text not null,
  message     text not null,
  status      text not null default 'new' check (status in ('new', 'done')),
  ip_hash     text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table public.staff_accounts (
  user_id           uuid primary key,                    -- auth.users.id (Supabase Auth)
  discord_user_id   text not null unique,
  display_name      text not null,
  avatar_url        text,
  roles             text[] not null default '{}',        -- admin | steward | redakteur
  driver_id         bigint references public.drivers (id) on delete set null,  -- für die Befangenheitsprüfung
  roles_checked_at  timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  check (roles <@ array['admin', 'steward', 'redakteur']::text[])
);

create table public.audit_log (
  id          bigint generated by default as identity primary key,
  actor_id    uuid,
  actor_name  text,
  action      text not null,                             -- create | update | delete | publish | …
  entity      text not null,                             -- Tabellenname
  entity_id   text,
  diff        jsonb,                                     -- {before, after}
  at          timestamptz not null default now(),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index audit_log_at_idx on public.audit_log (at desc);

-- Rate-Limit für öffentliche Formulare (ip_hash nach 30 Tagen gelöscht)
create table public.rate_limit_events (
  id          bigint generated by default as identity primary key,
  bucket      text not null,                             -- registration | incident | contact
  ip_hash     text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index rate_limit_events_lookup_idx on public.rate_limit_events (bucket, ip_hash, created_at desc);

-- Phase 2: UDP-/CSV-Import
create table public.import_batches (
  id           bigint generated by default as identity primary key,
  session_id   bigint not null references public.sessions (id) on delete cascade,
  source       text not null check (source in ('udp', 'csv')),
  raw          jsonb not null,
  mapping      jsonb,
  status       text not null default 'draft' check (status in ('draft', 'applied', 'discarded')),
  uploaded_by  uuid,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- updated_at-Trigger für alle Tabellen mit dieser Spalte
-- -----------------------------------------------------------------------------

do $$
declare
  t record;
begin
  for t in
    select c.table_name
    from information_schema.columns c
    where c.table_schema = 'public' and c.column_name = 'updated_at'
  loop
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.set_updated_at()',
      t.table_name || '_set_updated_at', t.table_name
    );
  end loop;
end;
$$;
