-- =============================================================================
-- Runde 2:
--   * slug_redirects: 301-Weiterleitungen bei Umbenennungen (Plan §2.2)
--   * tracks.map_url/map_credit: Streckenkarten als SVG-Umriss (Plan §7.5)
--   * open_positions.effort_en: Zeitaufwand zweisprachig (Plan §7.4)
--   * drivers_public: öffentliche Fahrer-Sicht ohne interne Felder (Plan §1, §6)
-- =============================================================================

alter table public.open_positions add column if not exists effort_en text;

alter table public.tracks add column if not exists map_url text;      -- SVG-Umriss (selbst erstellt oder offene Daten)
alter table public.tracks add column if not exists map_credit text;   -- Lizenz-/Quellenangabe

create table public.slug_redirects (
  id          bigint generated by default as identity primary key,
  entity      text not null check (entity in ('driver', 'team', 'season', 'news')),
  old_slug    text not null,
  new_slug    text not null,
  lang        text check (lang is null or lang in ('de', 'en')),   -- nur bei News (slug_de/slug_en)
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  check (old_slug <> new_slug)
);
create unique index slug_redirects_lookup_idx on public.slug_redirects (entity, old_slug, coalesce(lang, ''));

create trigger slug_redirects_set_updated_at
  before update on public.slug_redirects
  for each row execute function public.set_updated_at();

alter table public.slug_redirects enable row level security;
alter table public.slug_redirects force row level security;
create policy "public read" on public.slug_redirects for select to anon, authenticated using (true);

-- -----------------------------------------------------------------------------
-- Öffentliche Fahrer-Sicht: nur, was öffentlich sein darf. Twitch/YouTube nur, wenn der
-- Fahrer das wünscht (show_links). Eingabegerät ist intern.
-- Die Tabelle selbst ist für anon nicht mehr lesbar.
-- -----------------------------------------------------------------------------

drop policy if exists "public read" on public.drivers;

create view public.drivers_public
with (security_invoker = false, security_barrier = true)
as
select
  d.id,
  d.slug,
  d.gamertag,
  d.nationality_code,
  d.platform,
  null::text as input_device,          -- intern, nicht öffentlich
  d.status,
  d.reserve_order,
  d.joined_season_id,
  case when d.show_links then d.twitch_url end as twitch_url,
  case when d.show_links then d.youtube_url end as youtube_url,
  d.show_links,
  d.anonymized,
  d.created_at,
  d.updated_at
from public.drivers d;

revoke all on public.drivers_public from public;
grant select on public.drivers_public to anon, authenticated;
