/**
 * Seed-Generator (scripts/generate-seed-sql.ts): korrektes Escaping, Spalten passen zu den
 * Migrationen, und supabase/seed.sql ist auf dem Stand von src/lib/seed/base.ts.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { baseDataset } from '~/lib/seed/base';
import { demoDataset } from '~/lib/seed/demo';
import {
  buildBaseSeed,
  buildDemoSeed,
  buildSeedSql,
  diffDataset,
  insertStatements,
  loadSchema,
  parseSchema,
  setvalStatement,
  sqlString,
  sqlValue,
  TABLE_ORDER,
  type SeedDataset,
} from '../../scripts/generate-seed-sql';
import { PRIMARY_KEYS } from '~/lib/db/types';

const schema = loadSchema();

describe('SQL-Literale', () => {
  it('verdoppelt Hochkommas und lässt Backslashes stehen', () => {
    expect(sqlString("O'Neil")).toBe("'O''Neil'");
    expect(sqlString("''")).toBe("''''''");
    expect(sqlString('C:\\pfad')).toBe("'C:\\pfad'");
    expect(sqlString('Zeile 1\nZeile 2')).toBe("'Zeile 1\nZeile 2'");
  });

  it('lehnt NUL-Zeichen ab', () => {
    expect(() => sqlString(`a${String.fromCharCode(0)}b`)).toThrow();
  });

  it('formatiert Skalare', () => {
    expect(sqlValue(null, 'text')).toBe('NULL');
    expect(sqlValue(undefined, 'integer')).toBe('NULL');
    expect(sqlValue(true, 'boolean')).toBe('true');
    expect(sqlValue(false, 'boolean')).toBe('false');
    expect(sqlValue(42, 'integer')).toBe('42');
    expect(sqlValue(5.278, 'numeric(5, 3)')).toBe('5.278');
    expect(sqlValue('2026-11-05T20:00:00', 'timestamp')).toBe("'2026-11-05T20:00:00'");
    expect(() => sqlValue(Number.NaN, 'integer')).toThrow();
  });

  it('schreibt jsonb immer als JSON – auch null (settings.value ist NOT NULL)', () => {
    expect(sqlValue(null, 'jsonb')).toBe("'null'::jsonb");
    expect(sqlValue({ a: "it's", b: [1, null] }, 'jsonb')).toBe(`'{"a":"it''s","b":[1,null]}'::jsonb`);
    expect(sqlValue('liga', 'jsonb')).toBe(`'"liga"'::jsonb`);
  });

  it('schreibt Arrays als Postgres-Array-Literal mit Cast', () => {
    expect(sqlValue([25, 18, 15], 'integer[]')).toBe("'{25,18,15}'::integer[]");
    expect(sqlValue([], 'bigint[]')).toBe("'{}'::bigint[]");
    expect(sqlValue(['admin', 'a"b', 'c\\d'], 'text[]')).toBe(`'{"admin","a\\"b","c\\\\d"}'::text[]`);
    expect(() => sqlValue('x', 'integer[]')).toThrow();
  });

  it('lehnt Objekte in Nicht-JSON-Spalten ab', () => {
    expect(() => sqlValue({ a: 1 }, 'text')).toThrow();
  });
});

describe('Schema aus den Migrationen', () => {
  it('liest Tabellen, Typen und spätere add column-Anweisungen', () => {
    const parsed = parseSchema([
      `create table public.demo (
         id bigint generated by default as identity primary key,
         name text not null, -- Kommentar, mit Komma
         price numeric(5, 3),
         tags text[] not null default '{}',
         meta jsonb not null default '{}'::jsonb,
         at timestamp with time zone,
         unique (name),
         check (price > 0)
       );
       alter table public.demo add column if not exists extra integer[];`,
    ]);
    const cols = parsed.get('demo')!;
    expect([...cols.keys()]).toEqual(['id', 'name', 'price', 'tags', 'meta', 'at', 'extra']);
    expect(cols.get('tags')?.type).toBe('text[]');
    expect(cols.get('meta')?.type).toBe('jsonb');
    expect(cols.get('price')?.type).toBe('numeric(5, 3)');
    expect(cols.get('at')?.type).toBe('timestamptz');
    expect(cols.get('extra')?.type).toBe('integer[]');
  });

  it('kennt alle Tabellen aus src/lib/db/types.ts', () => {
    const missing = Object.keys(PRIMARY_KEYS).filter((t) => !schema.has(t));
    expect(missing).toEqual([]);
    expect([...TABLE_ORDER].sort()).toEqual(Object.keys(PRIMARY_KEYS).sort());
  });

  it('übernimmt Spalten aus späteren Migrationen und ignoriert Views, Indizes und Policies', () => {
    const parsed = parseSchema([
      `create table public.t (id bigint primary key, name text);`,
      `alter table public.t add column if not exists extra text;      -- Kommentar
       alter table public.t enable row level security;
       alter table public.t add column a text, add column b integer[], drop column name;
       create unique index t_idx on public.t (extra, coalesce(a, ''));
       create policy "public read" on public.t for select to anon using (true);
       create view public.t_public with (security_barrier = true) as select id from public.t;`,
    ]);
    expect([...parsed.get('t')!.keys()]).toEqual(['id', 'extra', 'a', 'b']);
    expect(parsed.get('t')!.get('b')?.type).toBe('integer[]');
    expect(parsed.has('t_public')).toBe(false);
  });

  it('kennt die Felder aus Migration 20260930090000 (Weiterleitungen, Streckenkarten, Zeitaufwand EN)', () => {
    expect(schema.get('tracks')?.has('map_url')).toBe(true);
    expect(schema.get('tracks')?.has('map_credit')).toBe(true);
    expect(schema.get('open_positions')?.has('effort_en')).toBe(true);
    expect([...(schema.get('slug_redirects')?.keys() ?? [])]).toEqual(['id', 'entity', 'old_slug', 'new_slug', 'lang', 'created_at', 'updated_at']);
    // Views sind keine Tabellen – drivers_public wird nie befüllt
    expect(schema.has('drivers_public')).toBe(false);
  });

  it('erkennt die Spezialtypen der Liga-Tabellen', () => {
    expect(schema.get('settings')?.get('value')?.type).toBe('jsonb');
    expect(schema.get('points_schemes')?.get('race_points')?.type).toBe('integer[]');
    expect(schema.get('incidents')?.get('involved_driver_ids')?.type).toBe('bigint[]');
    expect(schema.get('decisions')?.get('decided_by')?.type).toBe('uuid[]');
    expect(schema.get('rounds')?.get('local_start')?.type).toBe('timestamp');
  });
});

describe('INSERT-Erzeugung', () => {
  it('nutzt DEFAULT für fehlende Spalten und die Spaltenreihenfolge der Tabelle', () => {
    const [sql] = insertStatements(
      'teams',
      [
        { slug: 'a', name: 'A', short_name: 'A', color_hex: '#000000', id: 1 },
        { id: 2, slug: 'b', name: "B's", short_name: 'B', color_hex: '#FFFFFF', active: false },
      ],
      schema,
      'nothing',
    );
    expect(sql).toContain('insert into public.teams (id, slug, name, short_name, color_hex, active) values');
    expect(sql).toContain("(1, 'a', 'A', 'A', '#000000', DEFAULT)");
    expect(sql).toContain("(2, 'b', 'B''s', 'B', '#FFFFFF', false)");
    expect(sql).toMatch(/on conflict do nothing;$/);
  });

  it('aktualisiert im Demo-Modus über den Primärschlüssel', () => {
    const [sql] = insertStatements('settings', [{ key: 'registration', value: { state: 'open' }, is_public: true }], schema, 'update');
    expect(sql).toContain('on conflict (key) do update set value = excluded.value, is_public = excluded.is_public;');
  });

  it('bricht bei Spalten ab, die es in der Datenbank nicht gibt', () => {
    expect(() => insertStatements('teams', [{ id: 1, logo_url: 'x' }], schema, 'nothing')).toThrow(/teams\.logo_url/);
    expect(() => insertStatements('gibt_es_nicht', [{ id: 1 }], schema, 'nothing')).toThrow();
  });

  it('setzt Identitäts-Sequenzen hinter die höchste ID', () => {
    expect(setvalStatement('teams')).toBe(
      "select setval(pg_get_serial_sequence('public.teams', 'id'), coalesce(max(id), 0) + 1, false) from public.teams;",
    );
  });
});

describe('Seed-Dateien', () => {
  const base = baseDataset() as SeedDataset;

  it('supabase/seed.sql ist aktuell (sonst: npm run db:seed:generate)', () => {
    const committed = readFileSync(join(process.cwd(), 'supabase', 'seed.sql'), 'utf8').replace(/\r\n/g, '\n');
    const fresh = buildBaseSeed(base, schema);
    expect(committed === fresh, 'supabase/seed.sql weicht von baseDataset() ab').toBe(true);
  });

  it('enthält Basisdaten in Fremdschlüssel-Reihenfolge, keine Fahrer oder Ergebnisse', () => {
    const sql = buildSeedSql(base, schema, { title: 't', description: [], conflict: 'nothing' });
    const pos = (t: string) => sql.indexOf(`insert into public.${t} `);
    expect(pos('rules_versions')).toBeLessThan(pos('rules_sections'));
    expect(pos('points_schemes')).toBeGreaterThan(-1);
    expect(pos('teams')).toBeGreaterThan(-1);
    expect(pos('settings')).toBeGreaterThan(-1);
    expect(pos('drivers')).toBe(-1);
    expect(pos('results')).toBe(-1);
    // Einstellungen: öffentliche und private Schlüssel, null als JSON
    expect(sql).toContain(`('twitch_channel', 'null'::jsonb, true)`);
    expect(sql).toMatch(/\('webhooks', '\{[^']*\}'::jsonb, false\)/);
  });

  it('erzeugt den Demo-Datensatz vollständig passend zum Schema', () => {
    const full = demoDataset(new Date('2026-10-15T12:00:00Z')) as SeedDataset;
    const demoOnly = diffDataset(full, base);
    // Basistabellen ohne Änderung fallen weg, Demo-Overrides der Einstellungen bleiben
    expect(demoOnly.teams).toBeUndefined();
    expect(demoOnly.rules_sections).toBeUndefined();
    expect(demoOnly.settings?.map((s) => s.key).sort()).toEqual(['discord_counts', 'registration']);
    expect(demoOnly.results?.length).toBeGreaterThan(100);
    const sql = buildDemoSeed(full, base, schema, new Date('2026-10-15T12:00:00Z'));
    expect(sql).toContain('2026-10-15T12:00:00.000Z');
    expect(sql).toContain('insert into public.drivers ');
    expect(sql).toContain("'{9,10}'::bigint[]");
    expect(sql.indexOf('insert into public.seasons ')).toBeLessThan(sql.indexOf('insert into public.rounds '));
    expect(sql.indexOf('insert into public.rounds ')).toBeLessThan(sql.indexOf('insert into public.results '));
    expect(sql).toContain("select setval(pg_get_serial_sequence('public.results', 'id')");
    // Demo-Weiterleitung (E2E-Test /fahrer/kurvenkoenig-alt) und Streckenkarten-Spalten
    expect(sql).toMatch(/insert into public\.slug_redirects \(id, entity, old_slug, new_slug, lang\) values\n {2}\(1, 'driver', 'kurvenkoenig-alt', 'kurvenkoenig', NULL\)/);
    expect(sql).toContain("select setval(pg_get_serial_sequence('public.slug_redirects', 'id')");
  });
});
